### ISSUE TITLE
ETL Pipeline基盤整備: 設定ローダー(config_loader.py)実装

### ISSUE THREAD

**Issue by yu23ki14** [codeforjapan/BirdXplorer#156]
# ETL Pipeline基盤整備: 設定ローダー実装

関連Issue: #154 (ETLの柔軟性向上)

## 概要
設定駆動型ETLパイプラインの実現のため、YAML/JSON設定ファイルを読み込み、パイプライン設定オブジェクトに変換する設定ローダーを実装します。

### 1. 設定ローダー実装
- `pipeline/config/config_loader.py`: メイン実装
- `pipeline/config/models.py`: 設定データクラス定義
- YAML/JSON両対応の設定ファイル読み込み

### 2. 設定データ構造定義
```python
@dataclass
class ETLConfig:
    pipeline_name: str
    components: List[ComponentConfig]
    filters: List[FilterConfig]
    ai_settings: AIConfig
    extraction_settings: ExtractionConfig
```

### 3. 設定ファイルフォーマット例
```
pipeline_name: "language_first_pattern"
components:
  - name: "note_extractor"
    type: "NoteExtractorComponent"
  - name: "note_language_filter"
    type: "LanguageFilterComponent"
```

## 技術要件
PyYAML使用
型安全な設定読み込み
バリデーション機能
デフォルト設定対応

## 受け入れ条件

- 設定ローダーが実装されている
- YAML/JSON両方の形式に対応
- 設定バリデーション機能がある
- エラーハンドリングが適切
- 単体テストが実装されている
